services:
  postfix_relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postfix_relay
    ports:
    - "2500:25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
